# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:
# vim: set textwidth=80 colorcolumn=80:

version: '2'
services:
  gitbook:
    image: yanqd0/gitbook
    volumes:
      - .:/srv/gitbook
    ports:
      - 4000:4000
